export const optionAgenda = [
  {
    id: '01',
    nome: 'todos',
    categoria: 'todos',
    type: 'agenda',
  },
  {
    id: '02',
    nome: 'janeiro',
    categoria: 'janeiro',
    type: 'agenda',
  },
  {
    id: '03',
    nome: 'fevereiro',
    categoria: 'fevereiro',
    type: 'agenda',
  },
  {
    id: '04',
    nome: 'março',
    categoria: 'março',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'abril',
    categoria: 'abril',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'maio',
    categoria: 'maio',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'junho',
    categoria: 'junho',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'julho',
    categoria: 'julho',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'agosto',
    categoria: 'agosto',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'setembro',
    categoria: 'setembro',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'outubro',
    categoria: 'outubro',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'novembro',
    categoria: 'novembro',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'dezembro',
    categoria: 'dezembro',
    type: 'agenda',
  },
]