export const optionAgenda = [
  {
    id: '01',
    nome: 'todos',
    categoria: 'all',
    type: 'agenda',
  },
  {
    id: '02',
    nome: 'janeiro',
    categoria: 'janeiro',
    type: 'agenda',
  },
  {
    id: '03',
    nome: 'fevereiro',
    categoria: 'fevereiro',
    type: 'agenda',
  },
  {
    id: '04',
    nome: 'março',
    categoria: 'março',
    type: 'agenda',
  },
  {
    id: '05',
    nome: 'abril',
    categoria: 'abril',
    type: 'agenda',
  },
  {
    id: '06',
    nome: 'maio',
    categoria: 'maio',
    type: 'agenda',
  },
  {
    id: '07',
    nome: 'junho',
    categoria: 'junho',
    type: 'agenda',
  },
  {
    id: '08',
    nome: 'julho',
    categoria: 'julho',
    type: 'agenda',
  },
  {
    id: '09',
    nome: 'agosto',
    categoria: 'agosto',
    type: 'agenda',
  },
  {
    id: '10',
    nome: 'setembro',
    categoria: 'setembro',
    type: 'agenda',
  },
  {
    id: '11',
    nome: 'outubro',
    categoria: 'outubro',
    type: 'agenda',
  },
  {
    id: '12',
    nome: 'novembro',
    categoria: 'novembro',
    type: 'agenda',
  },
  {
    id: '13',
    nome: 'dezembro',
    categoria: 'dezembro',
    type: 'agenda',
  },
]
